language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: KspzQB8GX4K7lakmUvcGHBh62mLWPVAN0sbElDJSUWOlKpnfN8c4pNOxE7DYxWkjfgoMfvKF+K2646LHQB+nfbMKFmW689fKuOBAknWdcwVuQFfQo5grSxOtyC5FeFLx22cNFhDVIfw7y29jnlbLVISGemt1CsWYvEYshxI1UlN8qF0aZ+qsFVOu35Q6dbjet7SYF2IvM2gMMYLcrU696/vAApmYaW4pQjaFV1SVp8YUXPZp+dOxTGZOhTJflv9MJfPDIWLX0aRMucel+bxWviiNe82fo1t8sfF0Q9IrrEmmFOMP5HsEjIWUbVkFTDKN7SklNj3MGS+igrTN7Q+dpIxWRFrmd/cmLWfi59q3fD3qb1q/MVeiZvIXvZFcsA0OTqM268T2jvDbiEjGn46xpxLwR6Xjh4o/jmHBlAAV8CY2ZWwNX2FRzFjF8D6QdvmGDyOV9GSQQGPTN9vslTK8mihUBBPBh1x5iJPt58RBdKg09TqjoOk+UnqltJfzC5yZM1MFer/MrxVJ2LTjv1DmFf7OA5aFDtzzIXBu3arYaS8fe1a2sScM7u2lgYQ0KXZN594TsFmn/S7KNOxeAV4W8F2qB5NR8t8T0y926aD/FI+O87gohx90Ma2o4mLnB1crXkhXY9U17ysMweqYfU/fboUkdFB3xoovYV/4tl7ibGg=
  app: twitter-play-ui
