language: node_js
node_js:
  - "10"
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: GcgqYivvXoDf5/i9L57rHF0wq5S6IVZ6J3kefDD5TbfgFqXAK0/n6p/seH8daWlddHf69Mi93cBroIBh1ep2n1SwxdmIqG3ZS6P/l9jVhNVGuzlD2OEhUlHUofrGjuorY23OpmmceOKfu1GMsurpzqUTXGGM/Av+xysCSGUzDL2JQqcYLO9NkyBBs1wWeHJ6LUYrlMv7LZ3cmzMGXQecqUQk+L0KPMeMclow9rjhpetnrfAkDIlynx5sDClD2E9jF39TTRVIzJQ1VL05IIx03kYp+uPFoxTSvFi4wZyou4JbHJqYjzCA7eLwB1Cg1dYesUJEZCxbM0Npg0LY3bQ3t0zYYL/B0gVsgi69rhNn5Kd+eChE3T2p0lIsORLYIeYSqWv1J2HMaO7fJN9bzD151OvwnG0k0mqa9zc2POU8h2Ugl35rYPyqe6n2h20TfT/nixMfdUNrDj34x1s8/vVUPEYPsleV7YSqkvh+G8ylTZ3PQvPmHIil/YvHunLqd0o/NGMjHWeXFHFkltxStDQJUoRpCXT1n0/TO4ZWPaysBCH366h2MN4FYhMNvTGpTuiIkx6HRTTUUm21PbQGN4AX5NdV5LZAdKh3VXy9alJ5YUD59X4hFdkZ3QS8HemkQT0UbdYZQ1BTSVq6Q15+FRGkrhYNwAoi51kqryqxu/BzGZk=
  app: twitter-play-ui
